import {OAuth2Client} from "google-auth-library";


//this token is jwt token / which i varify manily in the jwt website also
const idToken= `eyJhbGciOiJSUzI1NiIsImtpZCI6IjY2MGVmM2I5Nzg0YmRmNTZlYmU4NTlmNTc3ZjdmYjJlOGMxY2VmZmIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiI4OTQyNDQwMTM0MDQtc2hzdjFtbDByZ3M3ZjVscXRnazZzbWtzbTZicjhwMHQuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiI4OTQyNDQwMTM0MDQtc2hzdjFtbDByZ3M3ZjVscXRnazZzbWtzbTZicjhwMHQuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMTA4OTM3MjIzMjI3NzM3NTE5MTQiLCJlbWFpbCI6ImFzaHJhZnVsbW9taW4yQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhdF9oYXNoIjoiSmp5S2txS3NtU1NvakVFNWpuXzhQUSIsImlhdCI6MTc0NzQ3NDM2OCwiZXhwIjoxNzQ3NDc3OTY4fQ.MGQTUDk_7wg6Sll4RH7DpV094zkHiKdIq5v8pFrN7968DTzc0b8oHVFXNvuq4CwHY4jZvQ-tcx-eRRgy3CcBX5RTCnETIyMKUlyK3KVMUhB2Zf6rQlmOk2Dbxqa9eHeSWRbYABSImy56UK7Xv3b5iw0YdI-ONP72f2HUAAyqhKz3fNV-VplKuul0mVzcmlsD3THqsMQGim7lBwkLfLFO8IraZHETFs3wJbtysZOIi1rpFIjQsPyZolQcXBsMeJPNK8TYf0JEF4OMcmjwNUGkLZCcjCV9svJV6vSxjPJZZMix-r-MetpUPOupMrFpuKLGCqcRAOTfPK2Fj6Ig_bFphQ`;


const client = new OAuth2Client();

const login_ticekt =await client.verifyIdToken({
   idToken: idToken
 }) // by than we can get user also info 
 
console.log(login_ticekt)